import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ReactNode } from 'react';
import cn from '@/lib/utils';
import ThemeProvider from './components/ThemeProvider';
import StoreProvider from './components/StoreProvider';
import LocaleSwitcher from './components/LocaleSwitcher';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: ReactNode;
  params: {
    locale: string;
  };
}>) {
  return (
    <html lang={locale}>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          'mx-auto flex min-h-screen max-w-4xl flex-col',
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <h1>Header</h1>
            <LocaleSwitcher />
            <div className="mt-20 grow">{children}</div>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
